### ISSUE TITLE
等了一个多小时都没有运行

### ISSUE THREAD

**Issue by youaremywind** [shanghaobo/NeteaseCloudMusicDayActions#1]
action等了一个多小时都没有运行

**Comment by shanghaobo** [comment]
后来我改成3小时运行一次了
cron:  '0 0/3 * * *'这个代表每3个小时运行一次

**Comment by shanghaobo** [comment]
调试时候可以先改成 on: [push]
代表提交时运行
如果配置好了再改为定时的
